<Project Sdk="Godot.NET.Sdk/4.5.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LuckerParty.Core/LuckerParty.Core.csproj" />
  </ItemGroup>
</Project>
